
import React from 'react';
import { 
  FileText, 
  Map as MapIcon, 
  Users, 
  User, 
  Plus, 
  Trash2, 
  Save, 
  ChevronRight, 
  ChevronDown,
  Layout,
  Settings,
  Download,
  Search,
  Sword,
  MessageSquare,
  Package,
  MapPin,
  Library,
  Globe,
  Bell,
  HeartHandshake,
  BookOpen,
  Shield,
  AlertTriangle,
  Gavel,
  Ban,
  CheckCircle,
  Activity,
  Terminal,
  Images
} from 'lucide-react';

// Using CSS variables allows these to change dynamically based on the [data-theme] attribute
export const COLORS = {
  bg: 'var(--bg-main)',
  surface: 'var(--bg-surface)',
  surfaceLight: 'var(--bg-surface)', // simplified mapping
  text: 'var(--text-main)',
  muted: 'var(--text-muted)',
  border: 'var(--border-color)',
  
  accentRed: 'var(--col-red)',
  accentYellow: 'var(--col-yellow)',
  accentBlue: 'var(--col-blue)',
  accentPurple: 'var(--col-purple)',
  accentTeal: 'var(--col-teal)',
  accentPink: 'var(--col-pink)',
  accentWhite: 'var(--col-white)', // Special case for "White" accents that need to invert in light mode
};

export const ICONS = {
  Scenario: <FileText size={20} />,
  Map: <MapIcon size={20} />,
  Characters: <Users size={20} />,
  Items: <Package size={20} />,
  Assets: <Images size={20} />,
  World: <Globe size={20} />,
  Profile: <User size={20} />,
  Campaigns: <Library size={20} />,
  Community: <Globe size={20} />,
  Friends: <HeartHandshake size={20} />,
  Messages: <MessageSquare size={20} />,
  Notifications: <Bell size={20} />,
  Guide: <BookOpen size={20} />,
  Add: <Plus size={20} />,
  Delete: <Trash2 size={18} />,
  Save: <Save size={18} />,
  ChevronRight: <ChevronRight size={18} />,
  ChevronDown: <ChevronDown size={18} />,
  Dashboard: <Layout size={20} />,
  Settings: <Settings size={20} />,
  Download: <Download size={20} />,
  Search: <Search size={20} />,
  Combat: <Sword size={18} />,
  Dialogue: <MessageSquare size={18} />,
  Loot: <Package size={18} />,
  Location: <MapPin size={18} />,
  Admin: <Shield size={20} />,
  Alert: <AlertTriangle size={18} />,
  Ban: <Ban size={16} />,
  Approve: <CheckCircle size={16} />,
  Moderation: <Gavel size={20} />,
  System: <Terminal size={20} />,
  Activity: <Activity size={20} />,
};
